export const chamberConfigs = [
  {
    key: "dail",
    label: "Dáil",
    title: "Vote Explorer: Dáil",
    subtitle:
      "Explore how TDs voted in Dáil Eireann with an interactive chamber map.",
    intro:
      "Votes cast in Dáil Eireann, referred to formally as divisions of the House, show how TDs aligned on motions, legislation, and other parliamentary business before the chamber.",
    debatePath: "dail",
    membersUrl: `${import.meta.env.BASE_URL}chambers/dail/members.json`,
    chamberSvgUrl: `${import.meta.env.BASE_URL}chambers/dail/chamber.svg`,
    seatAssignmentsUrl: `${import.meta.env.BASE_URL}chambers/dail/seatAssignmentsHistory.csv`,
    voteDetailsUrl: `${import.meta.env.BASE_URL}chambers/dail/data/voteDetails.json`,
    memberSingular: "TD",
    memberPlural: "TDs",
    emptySelectionTitle: "No TD selected",
    emptySelectionPrompt: "Click a seat in the chamber to inspect the vote.",
    filterLabel: "Filter TDs",
    searchPlaceholder: "Filter by TD, constituency or party",
    searchAriaLabel: "Filter by TD, constituency or party",
    mapDownloadPrefix: "dail_vote",
    placeholderInitial: "TD",
    secondaryLabel: "Constituency",
    getSecondaryValue: (seat) => seat.member?.Constituency || "",
    tertiaryLabel: "",
    getTertiaryValue: () => "",
    tooltipTopValue: () => "",
    tooltipBottomValue: (seat) => seat.member?.Constituency || "",
  },
  {
    key: "seanad",
    label: "Seanad",
    title: "Vote Explorer: Seanad",
    subtitle:
      "Explore how Senators voted in Seanad Eireann with an interactive chamber map.",
    intro:
      "Votes cast in the Seanad Chamber, referred to formally as divisions of the House, are an intrinsic part of parliamentary business. Each Senator is entitled to cast a vote and in doing so can influence each piece of business considered by Parliament.",
    debatePath: "seanad",
    membersUrl: `${import.meta.env.BASE_URL}chambers/seanad/members.json`,
    chamberSvgUrl: `${import.meta.env.BASE_URL}chambers/seanad/chamber.svg`,
    seatAssignmentsUrl: `${import.meta.env.BASE_URL}chambers/seanad/seatAssignmentsHistory.csv`,
    voteDetailsUrl: `${import.meta.env.BASE_URL}chambers/seanad/data/voteDetails.json`,
    memberSingular: "Senator",
    memberPlural: "Senators",
    emptySelectionTitle: "No Senator selected",
    emptySelectionPrompt: "Click a seat in the chamber to inspect the vote.",
    filterLabel: "Filter Senators",
    searchPlaceholder: "Filter by Senator, panel or party",
    searchAriaLabel: "Filter by Senator, panel or party",
    mapDownloadPrefix: "seanad_vote",
    placeholderInitial: "S",
    secondaryLabel: "Panel",
    getSecondaryValue: (seat) => seat.member?.Constituency || "",
    tertiaryLabel: "Group",
    getTertiaryValue: (seat) => seat.assignment?.group || "",
    tooltipTopValue: (seat) => seat.assignment?.group || "",
    tooltipBottomValue: (seat) => seat.member?.Constituency || "",
  },
];

export const defaultChamberKey = chamberConfigs[0].key;
